name: build
on:
  - push
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.16.x' 
      - name: Cmake build
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DMINIMAL_BUILD=Off
      - name: Build
        run: |
          cd build
          make VERBOSE=1
          make package
          make run-unit-tests
      - name: Test
        run: test/sysdig_trace_regression.sh build/userspace/sysdig/sysdig build/userspace/sysdig/chisels $GITHUB_REF