name: Build container
on:
  - push
jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        uses: docker/build-push-action@v2
        with:
          tags: sysdig/sysdig-builder:${{ github.sha }}
          context: docker/builder/
    outputs:
      builder_image: sysdig/sysdig-builder:${{ github.sha }}
  ci-test:
    runs-on: ubuntu-latest
    needs: builder
    container:
      image: ${{ needs.builder.outputs.builder_image }}
      options: '--entrypoint bash'
    steps:
      - name: Checkout Sysdig
        uses: actions/checkout@v2
        with:
          path: /source
      - name: Checkout libs
        uses: actions/checkout@v2
        with:
          repository: lucklypse/libs
          ref: fix/safer-strings-gcc-8
          path: /libs
      - name: Test
        run: build cmake

